-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 112,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = 34.5 / 64, y = 51 / 64},
  ["sprite_count"] = 24,
  ["width"] = 163,
}
