-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 134,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = -6 / 64, y = 7 / 64},
  ["sprite_count"] = 24,
  ["width"] = 92,
}
