-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 37,
  ["line_length"] = 3,
  ["scale"] = 1,
  ["shift"] = {x = 17 / 32, y = 14.5 / 32},
  ["sprite_count"] = 24,
  ["width"] = 126,
}
