-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 67,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = -3.5 / 32, y = 3 / 32},
  ["sprite_count"] = 24,
  ["width"] = 46,
}
