-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["metal-bandsaw-h-base"] = require("metal-bandsaw-h-base"),
  ["metal-bandsaw-h-idle"] = require("metal-bandsaw-h-idle"),
  ["metal-bandsaw-h-oxidation"] = require("metal-bandsaw-h-oxidation"),
  ["metal-bandsaw-h-shadow"] = require("metal-bandsaw-h-shadow"),
  ["metal-bandsaw-h-sparks"] = require("metal-bandsaw-h-sparks"),
  ["metal-bandsaw-h-workpiece"] = require("metal-bandsaw-h-workpiece"),
}
