-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 49,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = -0.5 / 64, y = 26.5 / 64},
  ["sprite_count"] = 36,
  ["width"] = 119,
}
