-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 66,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = -7 / 64, y = 86 / 64},
  ["sprite_count"] = 36,
  ["width"] = 96,
}
