-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 97,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = -16.5 / 64, y = 29.5 / 64},
  ["sprite_count"] = 36,
  ["width"] = 51,
}
