-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 130,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = -4.5 / 64, y = 27 / 64},
  ["sprite_count"] = 36,
  ["width"] = 81,
}
