-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 25,
  ["line_length"] = 4,
  ["scale"] = 1,
  ["shift"] = {x = -0 / 32, y = 13.5 / 32},
  ["sprite_count"] = 36,
  ["width"] = 60,
}
