-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 34,
  ["line_length"] = 5,
  ["scale"] = 1,
  ["shift"] = {x = -3.5 / 32, y = 43 / 32},
  ["sprite_count"] = 36,
  ["width"] = 49,
}
