-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["metal-extruder-h-base"] = require("metal-extruder-h-base"),
  ["metal-extruder-h-idle"] = require("metal-extruder-h-idle"),
  ["metal-extruder-h-oxidation"] = require("metal-extruder-h-oxidation"),
  ["metal-extruder-h-shadow"] = require("metal-extruder-h-shadow"),
  ["metal-extruder-h-sparks"] = require("metal-extruder-h-sparks"),
  ["metal-extruder-h-workpiece"] = require("metal-extruder-h-workpiece"),
}
