-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 50,
  ["line_length"] = 8,
  ["scale"] = 1,
  ["shift"] = {x = -1 / 32, y = 38 / 32},
  ["sprite_count"] = 36,
  ["width"] = 30,
}
