-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 46,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = 12 / 32, y = 22 / 32},
  ["sprite_count"] = 36,
  ["width"] = 64,
}
