-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 46,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = -1 / 64, y = 26 / 64},
  ["sprite_count"] = 36,
  ["width"] = 116,
}
