-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 90,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = 24 / 64, y = 44 / 64},
  ["sprite_count"] = 36,
  ["width"] = 126,
}
