-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 48,
  ["line_length"] = 5,
  ["scale"] = 1,
  ["shift"] = {x = 2 / 32, y = 7 / 32},
  ["sprite_count"] = 36,
  ["width"] = 68,
}
