-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 98,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = 0.5 / 64, y = 15 / 64},
  ["sprite_count"] = 24,
  ["width"] = 133,
}
