-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 57,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = -2.5 / 32, y = 9 / 32},
  ["sprite_count"] = 24,
  ["width"] = 36,
}
