-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 92,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = 6.5 / 64, y = 14 / 64},
  ["sprite_count"] = 24,
  ["width"] = 39,
}
