-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 41,
  ["line_length"] = 4,
  ["scale"] = 1,
  ["shift"] = {x = 16 / 32, y = 19 / 32},
  ["sprite_count"] = 24,
  ["width"] = 63,
}
