-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 25,
  ["line_length"] = 8,
  ["scale"] = 1,
  ["shift"] = {x = -2 / 32, y = -4 / 32},
  ["sprite_count"] = 24,
  ["width"] = 9,
}
