-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 60,
  ["line_length"] = 3,
  ["scale"] = 0.5,
  ["shift"] = {x = 47.5 / 64, y = 35 / 64},
  ["sprite_count"] = 24,
  ["width"] = 213,
}
