-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 36,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = -14 / 32, y = -1.5 / 32},
  ["sprite_count"] = 24,
  ["width"] = 23,
}
