-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 110,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -14 / 64, y = 26 / 64},
  ["sprite_count"] = 24,
  ["width"] = 50,
}
