-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["threader-h-base"] = require("threader-h-base"),
  ["threader-h-idle"] = require("threader-h-idle"),
  ["threader-h-oxidation"] = require("threader-h-oxidation"),
  ["threader-h-shadow"] = require("threader-h-shadow"),
  ["threader-h-sparks"] = require("threader-h-sparks"),
  ["threader-h-workpiece"] = require("threader-h-workpiece"),
}
