-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 88,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 10 / 64, y = 44 / 64},
  ["sprite_count"] = 24,
  ["width"] = 102,
}
