-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 34,
  ["line_length"] = 4,
  ["scale"] = 1,
  ["shift"] = {x = 1.5 / 32, y = 14 / 32},
  ["sprite_count"] = 24,
  ["width"] = 61,
}
