-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 49,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = -39.5 / 64, y = 19.5 / 64},
  ["sprite_count"] = 24,
  ["width"] = 33,
}
