-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 56,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = -15 / 64, y = 2 / 64},
  ["sprite_count"] = 24,
  ["width"] = 48,
}
