-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 28,
  ["line_length"] = 5,
  ["scale"] = 1,
  ["shift"] = {x = -7.5 / 32, y = 1 / 32},
  ["sprite_count"] = 24,
  ["width"] = 25,
}
