-- Generated by spritter v0.5.1 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 1,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 0 / 64, y = 0 / 64},
  ["sprite_count"] = 25,
  ["width"] = 1,
}
