-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 63,
  ["line_length"] = 5,
  ["scale"] = 1,
  ["shift"] = {x = -15 / 32, y = 0.5 / 32},
  ["sprite_count"] = 25,
  ["width"] = 64,
}
