-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 103,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = -1 / 64, y = -13.5 / 64},
  ["sprite_count"] = 25,
  ["width"] = 142,
}
