-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["hr-electroplater-h-base"] = require("hr-electroplater-h-base"),
  ["hr-electroplater-h-idle"] = require("hr-electroplater-h-idle"),
  ["hr-electroplater-h-shadow"] = require("hr-electroplater-h-shadow"),
  ["hr-electroplater-h-sparks"] = require("hr-electroplater-h-sparks"),
  ["hr-electroplater-h-oxidation"] = require("hr-electroplater-h-oxidation"),
  ["hr-electroplater-h-workpiece"] = require("hr-electroplater-h-workpiece"),
}
