-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 92,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -9 / 64, y = -4 / 64},
  ["sprite_count"] = 25,
  ["width"] = 46,
}
