-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 34,
  ["line_length"] = 3,
  ["scale"] = 1,
  ["shift"] = {x = 26 / 32, y = 14 / 32},
  ["sprite_count"] = 25,
  ["width"] = 112,
}
