-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 87,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 3.5 / 64, y = 3.5 / 64},
  ["sprite_count"] = 25,
  ["width"] = 123,
}
