-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 109,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = 18.5 / 64, y = 14.5 / 64},
  ["sprite_count"] = 25,
  ["width"] = 85,
}
