return
  {["v_workpiece"] = {
    ["height"] = 72,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = 16.5 / 32, y = -26 / 32},
    ["sprite_count"] = 31,
    ["width"] = 49,
  },
  ["v_shadow"] = {
    ["height"] = 80,
    ["line_length"] = 5,
    ["scale"] = 1,
    ["shift"] = {x = -22.5 / 32, y = -38 / 32},
    ["sprite_count"] = 31,
    ["width"] = 125,
  },
  ["v_sparks"] = {
    ["height"] = 59,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = 34.5 / 32, y = -43.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 39,
  },
  ["v_oxidation"] = {
    ["height"] = 71,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = 16 / 32, y = -26.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 44,
  },
  ["v_base"] = {
    ["height"] = 111,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = 6.5 / 32, y = -20.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 77,
  },
  ["v_idle"] = {
    ["height"] = 111,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = 6.5 / 32, y = -20.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 77,
  },
  ["h_workpiece"] = {
    ["height"] = 78,
    ["line_length"] = 5,
    ["scale"] = 1,
    ["shift"] = {x = 0 / 32, y = -14 / 32},
    ["sprite_count"] = 31,
    ["width"] = 116,
  },
  ["h_sparks"] = {
    ["height"] = 75,
    ["line_length"] = 7,
    ["scale"] = 1,
    ["shift"] = {x = -30 / 32, y = -39.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 60,
  },
  ["h_shadow"] = {
    ["height"] = 58,
    ["line_length"] = 4,
    ["scale"] = 1,
    ["shift"] = {x = -34 / 32, y = -34 / 32},
    ["sprite_count"] = 31,
    ["width"] = 190,
  },
  ["h_oxidation"] = {
    ["height"] = 70,
    ["line_length"] = 5,
    ["scale"] = 1,
    ["shift"] = {x = -1 / 32, y = -17 / 32},
    ["sprite_count"] = 31,
    ["width"] = 114,
  },
  ["h_base"] = {
    ["height"] = 107,
    ["line_length"] = 5,
    ["scale"] = 1,
    ["shift"] = {x = -1.5 / 32, y = -12.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 137,
  },
  ["h_idle"] = {
    ["height"] = 107,
    ["line_length"] = 5,
    ["scale"] = 1,
    ["shift"] = {x = -1.5 / 32, y = -12.5 / 32},
    ["sprite_count"] = 31,
    ["width"] = 137,
  }
}