-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 69,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = 13.5 / 64, y = 29.5 / 64},
  ["sprite_count"] = 25,
  ["width"] = 33,
}
