-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 40,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = 3 / 32, y = 11 / 32},
  ["sprite_count"] = 25,
  ["width"] = 24,
}
