-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 72,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = 1.5 / 32, y = 8 / 32},
  ["sprite_count"] = 25,
  ["width"] = 41,
}
