-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 28,
  ["line_length"] = 3,
  ["scale"] = 1,
  ["shift"] = {x = 19.5 / 32, y = 17 / 32},
  ["sprite_count"] = 25,
  ["width"] = 99,
}
