-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 36,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = 7 / 32, y = 15 / 32},
  ["sprite_count"] = 25,
  ["width"] = 18,
}
