-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 54,
  ["line_length"] = 3,
  ["scale"] = 0.5,
  ["shift"] = {x = 39 / 64, y = 34 / 64},
  ["sprite_count"] = 25,
  ["width"] = 196,
}
