-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 119,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 17 / 64, y = 8.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 174,
}
