-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 137,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -5.5 / 64, y = 18.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 83,
}
