-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 78,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = 11.5 / 64, y = 10 / 64},
  ["sprite_count"] = 31,
  ["width"] = 81,
}
