-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 63,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = 35.5 / 64, y = 33.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 199,
}
