-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 69,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = -2.5 / 32, y = 9 / 32},
  ["sprite_count"] = 31,
  ["width"] = 42,
}
