-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 40,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = 5.5 / 32, y = 5 / 32},
  ["sprite_count"] = 31,
  ["width"] = 41,
}
