-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 101,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 27 / 64, y = 47.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 138,
}
