-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 138,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = 0.5 / 64, y = 13 / 64},
  ["sprite_count"] = 36,
  ["width"] = 91,
}
