-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 108,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = 13.5 / 64, y = 17 / 64},
  ["sprite_count"] = 36,
  ["width"] = 135,
}
