-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 84,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 31 / 64, y = 37 / 64},
  ["sprite_count"] = 36,
  ["width"] = 142,
}
