-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 55,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = 6.5 / 32, y = 8.5 / 32},
  ["sprite_count"] = 36,
  ["width"] = 69,
}
