-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 69,
  ["line_length"] = 8,
  ["scale"] = 1,
  ["shift"] = {x = 0.5 / 32, y = 6 / 32},
  ["sprite_count"] = 36,
  ["width"] = 46,
}
