-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 126,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = -0 / 64, y = 6 / 64},
  ["sprite_count"] = 36,
  ["width"] = 76,
}
