-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 31,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = -15 / 32, y = 22 / 32},
  ["sprite_count"] = 31,
  ["width"] = 25,
}
