-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 36,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = -8 / 32, y = 13.5 / 32},
  ["sprite_count"] = 31,
  ["width"] = 23,
}
