-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 36,
  ["line_length"] = 5,
  ["scale"] = 1,
  ["shift"] = {x = 0.5 / 32, y = 8 / 32},
  ["sprite_count"] = 31,
  ["width"] = 59,
}
