-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 71,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -16 / 64, y = 26.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 44,
}
