-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 75,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = 30.5 / 64, y = 39.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 61,
}
