-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 59,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -30 / 64, y = 43.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 48,
}
