-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["hr-drill-press-v-base"] = require("hr-drill-press-v-base"),
  ["hr-drill-press-v-idle"] = require("hr-drill-press-v-idle"),
  ["hr-drill-press-v-oxidation"] = require("hr-drill-press-v-oxidation"),
  ["hr-drill-press-v-shadow"] = require("hr-drill-press-v-shadow"),
  ["hr-drill-press-v-sparks"] = require("hr-drill-press-v-sparks"),
  ["hr-drill-press-v-workpiece"] = require("hr-drill-press-v-workpiece"),
}
