-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 78,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = -0 / 64, y = 14 / 64},
  ["sprite_count"] = 31,
  ["width"] = 116,
}
