-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 107,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = 1.5 / 64, y = 12.5 / 64},
  ["sprite_count"] = 31,
  ["width"] = 137,
}
