-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 71,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = -1 / 32, y = 2 / 32},
  ["sprite_count"] = 24,
  ["width"] = 43,
}
