-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["welder-v-base"] = require("welder-v-base"),
  ["welder-v-idle"] = require("welder-v-idle"),
  ["welder-v-oxidation"] = require("welder-v-oxidation"),
  ["welder-v-shadow"] = require("welder-v-shadow"),
  ["welder-v-sparks"] = require("welder-v-sparks"),
  ["welder-v-workpiece"] = require("welder-v-workpiece"),
}
