-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 40,
  ["line_length"] = 4,
  ["scale"] = 1,
  ["shift"] = {x = 20.5 / 32, y = 17.5 / 32},
  ["sprite_count"] = 24,
  ["width"] = 76,
}
