-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 31,
  ["line_length"] = 3,
  ["scale"] = 1,
  ["shift"] = {x = 16.5 / 32, y = 17.5 / 32},
  ["sprite_count"] = 29,
  ["width"] = 97,
}
