-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 78,
  ["line_length"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {x = 38.5 / 64, y = 36 / 64},
  ["sprite_count"] = 29,
  ["width"] = 155,
}
