-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 16,
  ["line_length"] = 6,
  ["scale"] = 1,
  ["shift"] = {x = -7.5 / 32, y = 16.5 / 32},
  ["sprite_count"] = 29,
  ["width"] = 16,
}
