-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 67,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = -2.5 / 32, y = 5 / 32},
  ["sprite_count"] = 29,
  ["width"] = 40,
}
