-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["bender-v-base"] = require("bender-v-base"),
  ["bender-v-idle"] = require("bender-v-idle"),
  ["bender-v-oxidation"] = require("bender-v-oxidation"),
  ["bender-v-shadow"] = require("bender-v-shadow"),
  ["bender-v-sparks"] = require("bender-v-sparks"),
  ["bender-v-workpiece"] = require("bender-v-workpiece"),
}
