-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 109,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = -8 / 64, y = 9.5 / 64},
  ["sprite_count"] = 29,
  ["width"] = 46,
}
