-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 81,
  ["line_length"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {x = -5.5 / 64, y = 6.5 / 64},
  ["sprite_count"] = 29,
  ["width"] = 111,
}
