-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 134,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -5 / 64, y = 11 / 64},
  ["sprite_count"] = 29,
  ["width"] = 80,
}
