-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 30,
  ["line_length"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {x = -15 / 64, y = 33 / 64},
  ["sprite_count"] = 29,
  ["width"] = 30,
}
