-- Generated by spritter v0.5.3 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 107,
  ["line_length"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {x = -10 / 64, y = 8.5 / 64},
  ["sprite_count"] = 29,
  ["width"] = 42,
}
